services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - app-network
    develop:
        watch:
          - action: sync+restart
            path: ./nginx/nginx.conf
            target: /etc/nginx/nginx.conf

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    networks:
      - app-network
    expose:
      - "3000"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app

  ml:
    build:
      context: ./ml
      dockerfile: Dockerfile
    ports:
    - "8000:8000"
    networks:
    - app-network
    develop:
      watch:
        - action: sync+restart
          path: ./ml
          target: /app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - app-network
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /app

networks:
  app-network:
    driver: bridge