export const HOME = "/"
export const SIGN_IN = "/signin"
export const SIGN_UP = "/signup"
export const ABOUT = "/about"
export const PROFILE = "/profile"

export const UPLOAD_FILE = "/uploadfile"
export const GET_HISTORY = "/gethistory"
export const HISTORY_IMAGE = "/history/image"
export const CLASSIFICATION_JOBS_ACTIVE = "/classification-jobs/active"