export const HOME = "/"
export const SIGN_IN = "/signin"
export const SIGN_UP = "/signup"
export const VERIFY_EMAIL = "/verify-email"
export const ABOUT = "/about"
export const PROFILE = "/profile"
export const API_DOCS = "/api-docs"

export const ME = "/me"
export const ME_PROFILE = "/me/profile"
export const ME_AVATAR = "/me/avatar"
export const ME_API_TOKEN = "/me/api-token"
export const ME_API_TOKEN_ROTATE = "/me/api-token/rotate"
export const CHANGE_PASSWORD = "/change-password"
export const RESEND_VERIFICATION_EMAIL = "/resend-verification-email"
export const UPLOAD_FILE = "/uploadfile"
export const GET_HISTORY = "/gethistory"
export const HISTORY_IMAGE = "/history/image"
export const CLASSIFICATION_JOBS_ACTIVE = "/classification-jobs/active"

export const API_V1_PREFIX = "/api/v1"